#- name:  
- name: Join workers
  delegate_to: "{{ item }}"
  shell: "if ! [ -e /etc/kubernetes/kubelet.conf ]; then 
  kubeadm join --token {{ kubeadm_token.stdout }} {{ control_plane_endpoint }}:6443 
  --discovery-token-ca-cert-hash sha256:{{ token_ca_hash.stdout }}; fi"
  #with_items: "{{ groups['kube-node'][0] }}"
  with_items: "{{ groups['kube-node'] }}"
  tags: workers