- name: Add chart repo for Metrics server
  kubernetes.core.helm_repository:
    repo_url: "https://kubernetes-sigs.github.io/metrics-server/"
    name: metrics-server

- name: Deploy Metrics server
  helm:
    name: metrics-server
    chart_ref: metrics-server/metrics-server
    release_namespace: kube-system