# - name: Install flannel
#   shell: "kubectl apply -f https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml"
#   register: flannel_install

# - name: Print flannel installation result
#   debug:
#     msg: flannel_install
- name: Create values file
  template:
    src: values.j2
    dest: /tmp/helm-values.yaml

- name: Add stable chart repo
  kubernetes.core.helm_repository:
    name: flannel
    repo_url: "https://flannel-io.github.io/flannel/"
    
- name: Deploy Helm chart
  kubernetes.core.helm:
    name: flannel
    chart_ref: flannel/flannel 
    create_namespace: true
    release_namespace: flannel
    atomic: true
    values_files:
    - /tmp/helm-values.yaml
  register: flannel_install

- name: Print flannel installation result
  debug:
    msg: flannel_install