- hosts: all
  gather_facts:
  tags: always

- hosts: all
  become: yes
  roles:
  - hosts
  tags: hosts, prepare

- hosts: all
  become: yes
  roles:
  - containerd
  tags: cri, containerd, prepare

- hosts: all
  become: yes
  roles:
  - modules-load
  tags: modules, prepare

- hosts: all
  become: yes
  roles:
  - sysctl
  tags: sysctl, prepare

- hosts: all
  become: yes
  roles:
  - kube-packages
  tags: kube-packages, prepare

- hosts: all
  become: yes
  roles:
  - kubectl-aliases
  tags: kubectl

- hosts: kube-master[0]
  become: yes
  roles:
  - kubeadm
  tags: master-init, masters

- hosts: kube-master[0]
  become: yes
  roles:
  - role: kubeadm-join
  #tags: workers

- hosts: kube-master[0]
  become: yes
  roles:
  - role: kubeadm-join
  #tags: masters

- hosts: kube-master[0]
  become: yes
  roles:
  - flannel
  tags: cni