- name: Create .kube dir
  file:
    path: /root/.kube
    state: directory
    
- name: Copy kubeconfig
  copy: 
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    remote_src: true
