- name: Kubeadm init debug vars
  debug:
  #var: ansible_facts
    var: ansible_facts["{{ interface }}"]["ipv4"]["address"]
  #msg: "{{ devices.enp0s8.device }}"
  #msg: "{{ ansible_all_ipv4_addresses }}"
  register: apiserver_advertise_address

#- name: debug var
#  debug:
#    msg: "{{ apiserver_advertise_address }}"

- name: Kubeadm init command and args
  vars: 
    ip: "{{ apiserver_advertise_address.values() | first }}"
  debug: 
    msg: "kubeadm --apiserver-advertise-address={{ ip }} 
    --control-plane-endpoint= {{ control_plane_endpoint }}
    --pod-network-cidr= {{ pods_cidr }}"

- name: Kubeadm run init
  shell: "if ! [ -e /etc/kubernetes/kubelet.conf ]; then 
  kubeadm init --apiserver-advertise-address={{ apiserver_advertise_address.values() | first }} 
  --control-plane-endpoint={{ control_plane_endpoint }} 
  --pod-network-cidr={{ pods_cidr }} --upload-certs; fi"
  register: kubeadm_init_out
  ignore_errors: true

- name: Show kubeadm init output
  debug:
    msg: "{{ kubeadm_init_out }}"

- name: Copy kubeconfig
  include_tasks: kubeconfig.yml